import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ProductProvider } from "@/context/ProductContext";
import { Toaster } from "sonner";
import { InvoiceProvider } from "@/context/InvoiceContext";
import { Navbar } from "@/components/NavBar";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}
      >
        <AuthProvider>
          <ProductProvider>
            <InvoiceProvider>
              <Navbar />
              {children}
              <Toaster position="bottom-right" />
            </InvoiceProvider>
          </ProductProvider>
        </AuthProvider>

      </body>
    </html>
  );
}
